# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twttr', '0002_auto_20171129_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='location',
            new_name='genre',
        ),
    ]
