# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twttr', '0004_auto_20171130_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('text', models.CharField(default='normal', max_length=120)),
                ('category', models.CharField(default='normal', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twttr.TwitterUser')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twttr.Network')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twttr.Show')),
            ],
        ),
    ]
