# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 23:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twttr', '0005_twittercontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittercontent',
            name='timeoftweet',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 23, 25, 2, 387276)),
        ),
    ]
