# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 04:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twttr', '0009_auto_20171201_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittercontent',
            name='text',
            field=models.CharField(default='normal', max_length=560),
        ),
        migrations.AlterField(
            model_name='twittercontent',
            name='timeoftweet',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 4, 6, 17, 201058)),
        ),
    ]
