# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-05 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twttr', '0011_auto_20171204_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittercontent',
            name='timeoftweet',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 5, 19, 36, 36, 798715)),
        ),
    ]
