# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 15:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twttr', '0015_auto_20171205_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittercontent',
            name='timeoftweet',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 6, 15, 14, 29, 477899)),
        ),
    ]
