# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twttr', '0016_auto_20171206_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittercontent',
            name='timeoftweet',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 6, 15, 22, 58, 292783)),
        ),
    ]
