# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twttr', '0017_auto_20171206_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittercontent',
            name='timeoftweet',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 6, 15, 27, 29, 38442)),
        ),
    ]
