# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 18:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twttr', '0018_auto_20171206_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittercontent',
            name='timeoftweet',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 6, 18, 34, 51, 406983)),
        ),
    ]
