# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-07 06:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twttr', '0021_auto_20171206_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='critics_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='twitter_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='twittercontent',
            name='timeoftweet',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 6, 10, 7, 406104)),
        ),
    ]
