# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-07 06:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twttr', '0022_auto_20171207_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittercontent',
            name='timeoftweet',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 6, 26, 28, 16785)),
        ),
    ]
