# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 03:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twttr', '0024_auto_20171218_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittercontent',
            name='timeoftweet',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 3, 50, 46, 437120)),
        ),
    ]
