# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 04:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twttr', '0025_auto_20171218_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittercontent',
            name='timeoftweet',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 4, 13, 51, 430414)),
        ),
    ]
