# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 06:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twttr', '0028_auto_20180112_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittercontent',
            name='RNN_sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twittercontent',
            name='actual_sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twittercontent',
            name='timeoftweet',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 6, 22, 30, 901792)),
        ),
    ]
