# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-05 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('review_url', models.CharField(max_length=560)),
                ('review_polarity', models.CharField(max_length=120)),
                ('review_subjectivity', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('critic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critic.Critic')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critic.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='critic',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='critic.Organization'),
        ),
    ]
