# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0005_reviews_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='thumbsup',
            field=models.CharField(default='Positive', max_length=150),
        ),
    ]
