# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-07 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0006_reviews_thumbsup'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='critics_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='twitter_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
