# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0007_auto_20171207_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=280),
        ),
    ]
