# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0008_auto_20171218_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
