# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0009_auto_20171218_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='RNN_sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='actual_sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
