# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 06:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twttr', '0028_auto_20180112_0601'),
        ('RNN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNNTwitterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('markedsentiment', models.IntegerField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twttr.TwitterContent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
